---
- name: Finish obj01-06 text editing lab
  hosts: servera
  gather_facts: false

  tasks:
    - name: Remove exercise data
      ansible.builtin.file:
        path: /home/student/rhcsa-lab/obj01-06
        state: absent
