---
- name: Prepare obj11-03
  hosts: servera
  gather_facts: false
  become: true
  tasks:
    - ansible.builtin.service:
        name: autofs
        state: stopped
        enabled: false
      failed_when: false

    - ansible.builtin.file:
        path: /etc/auto.master.d/rhcsa11.autofs
        state: absent

    - ansible.builtin.file:
        path: /etc/auto.rhcsa11
        state: absent

    - ansible.builtin.file:
        path: /home/student/direct11
        state: absent

    - ansible.builtin.file:
        path: /home/student/rhcsa-lab/obj11-03
        state: absent

    - ansible.builtin.file:
        path: /home/student/rhcsa-lab/obj11-03/output
        state: directory
        owner: student
        group: student
        mode: "0755"
