---
- name: Prepare obj02-05 password aging lab
  hosts: servera
  gather_facts: false
  become: true
  tasks:
    - ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: true
      loop: [aginguser1, aginguser2]
    - ansible.builtin.user:
        name: "{{ item }}"
        shell: /bin/bash
        state: present
      loop: [aginguser1, aginguser2]
