---
- name: Finish obj01-01 file operations lab
  hosts: servera
  gather_facts: false

  tasks:
    - name: Remove exercise data
      ansible.builtin.file:
        path: /home/student/rhcsa-lab/obj01-01
        state: absent
