#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

echo "== OBJ10 SELinux/firewalld safety contract =="

mapfile -t labs < <(find "$ROOT/labs/10-selinux-firewalld" -mindepth 2 -maxdepth 2 -name lab.yml | sort)
[[ "${#labs[@]}" -eq 9 ]] || {
  echo "FAIL: expected 9 OBJ10 labs, got ${#labs[@]}"
  exit 1
}

for f in "${labs[@]}"; do
  grep -q '^status: ready$' "$f" || {
    echo "FAIL: every OBJ10 lab must be runtime-gradeable"
    exit 1
  }
done

# Never normalize the environment by disabling SELinux.
if grep -RIEq 'SELINUX=disabled|selinux=0' \
  "$ROOT/labs/10-selinux-firewalld" \
  "$ROOT/tests/reference-solutions"/obj10-*.sh \
  "$ROOT/ansible/prepare-objective10.yml"; then
  echo "FAIL: OBJ10 must never disable SELinux"
  exit 1
fi

# Avoid teaching policy-module generation as a shortcut for ordinary labeling mistakes.
if grep -RIEq 'audit2allow|semodule[[:space:]]+-i' \
  "$ROOT/tests/reference-solutions"/obj10-*.sh; then
  echo "FAIL: OBJ10 reference solutions must not use audit2allow/semodule shortcuts"
  exit 1
fi

# Firewall exercises must not jeopardize the SSH path.
if grep -RIEq \
  -- '--remove-service=ssh|--set-default-zone|--change-interface|--remove-interface' \
  "$ROOT/labs/10-selinux-firewalld" \
  "$ROOT/tests/reference-solutions"/obj10-*.sh; then
  echo "FAIL: OBJ10 firewall path may not remove SSH or move the management interface"
  exit 1
fi

# Reference solvers intentionally feed scripts through stdin.
for solver in "$ROOT"/tests/reference-solutions/obj10-*.sh; do
  if grep -Eq "ssh[[:space:]]+-n[[:space:]]+servera.*<<['\"]?EOS['\"]?" "$solver"; then
    echo "FAIL: ${solver#"$ROOT"/} combines ssh -n with a here-document"
    exit 1
  fi
done

grep -Rqs 'semanage fcontext' "$ROOT/labs/10-selinux-firewalld" || {
  echo "FAIL: OBJ10 must cover persistent file contexts"
  exit 1
}
grep -Rqs 'setsebool -P' "$ROOT/labs/10-selinux-firewalld" || {
  echo "FAIL: OBJ10 must cover persistent SELinux Booleans"
  exit 1
}
grep -Rqs 'ausearch -m AVC' "$ROOT/labs/10-selinux-firewalld" || {
  echo "FAIL: OBJ10 must cover AVC investigation"
  exit 1
}
grep -Rqs 'semanage port' "$ROOT/labs/10-selinux-firewalld" || {
  echo "FAIL: OBJ10 must cover SELinux port labeling"
  exit 1
}
grep -Rqs 'firewall-cmd --permanent' "$ROOT/labs/10-selinux-firewalld" || {
  echo "FAIL: OBJ10 must cover persistent firewalld configuration"
  exit 1
}

echo "OK: 9 labs cover SELinux and firewalld without weakening the management path"
# obj10-05 must not scan the entire accumulated audit log in the reference path.
solver="$ROOT/tests/reference-solutions/obj10-05.sh"
setup="$ROOT/labs/10-selinux-firewalld/05-selinux-avc-troubleshooting/setup.yml"

grep -q 'ausearch -if input/avc.audit -m AVC' "$solver" || {
  echo "FAIL: obj10-05 must analyze the bounded real AVC sample with ausearch -if"
  exit 1
}

if grep -q 'ausearch -m AVC -ts recent' "$solver"; then
  echo "FAIL: obj10-05 reference solver must not perform an unbounded live audit-log scan"
  exit 1
fi

grep -q 'tail -n 5000 /var/log/audit/audit.log' "$setup" || {
  echo "FAIL: obj10-05 setup must capture a bounded tail of the live audit log"
  exit 1
}

grep -q 'path="/srv/avc10/index.html"' "$setup" || {
  echo "FAIL: obj10-05 setup must capture the AVC generated by its own resource"
  exit 1
}

echo "OK: obj10-05 uses a bounded real AVC sample for deterministic ausearch practice"
