---
- name: Finish obj04-01 positional parameter lab
  hosts: servera
  gather_facts: false
  become: true
  tasks:
    - ansible.builtin.file:
        path: /home/student/rhcsa-lab/obj04-01
        state: absent
