---
- name: Finish obj04-06 file-loop lab
  hosts: servera
  gather_facts: false
  become: true
  tasks:
    - ansible.builtin.file:
        path: /home/student/rhcsa-lab/obj04-06
        state: absent
