---
- name: Finish obj03-06 update lab
  hosts: servera
  gather_facts: false
  become: true
  tasks:
    - ansible.builtin.command: rpm -e rhcsa-update-demo
      changed_when: false
      failed_when: false
    - ansible.builtin.file:
        path: /etc/yum.repos.d/rhcsa-update.repo
        state: absent
