---
- name: Finish obj04-05 argument-loop lab
  hosts: servera
  gather_facts: false
  become: true
  tasks:
    - ansible.builtin.file:
        path: /home/student/rhcsa-lab/obj04-05
        state: absent
